<?php
	// Breadcrumbs
	$this->breadcrumbs()->append($this->translate('resources'));
		
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            
            <div class="panel-heading">
            	<?php echo $this->translate('resource_lister') ?>
            	
            	<div class="pull-right" >
            		
					<a 
						href="<?php echo $this->acmUrl('editer', 'resource', 'admin')?>"
						class="btn btn-primary btn-sx" 
						role="button" 						
						data-placement="top" 
						data-toggle="tooltip"
						data-original-title="<?php echo $this->translate('resource_ajouter') ?>"
					>
						<i class="fa fa-plus-square"></i>						
					</a>     
            	</div>
            	<div class="row"></div>
            </div>
            
            <div class="panel-body">
				
				<?php echo $this->flashMessengerStatus() ?>
				            
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>
                                	<?php echo $this->translate('resource_id')?>
                                </th>
                                
                                <th >
                                	<?php echo $this->translate('resource_module')?>
                                </th>
                                
                                <th>
                                	<?php echo $this->translate('resource_controller')?>
                                </th>
                                
                                <th>
                                	<?php echo $this->translate('resource_action')?>
                                </th>
                                
                                <th>
                                	<?php echo $this->translate('resource_description')?>
                                </th>
                                
                                <th>
                                	<?php echo $this->translate('actions')?>
                                </th>
                                
                            </tr>
                        </thead>
                        
                        <tbody>
                        <?php if ( is_array($this->resourcesList) && count($this->resourcesList)) : ?>
                        
                        <?php foreach ($this->resourcesList as $resourceRow) : ?>
                        <tr>
                        	<td class="td-width-5">
                        		<?php echo $this->escape($resourceRow['id']) ?>
                        	</td>
                        	
                        	<td class="td-width-15">
                        		<?php echo $this->escape($resourceRow['module']) ?>
                        	</td>
                        	
                        	<td class="td-width-15">
                        		<?php echo $this->escape($resourceRow['controller']) ?>
                        	</td>
                        	
                        	<td class="td-width-20">
                        		<?php echo $this->escape($resourceRow['action']) ?>
                        	</td>
                        	
                        	<td class="td-width-30">
                        		<?php echo $this->escape($resourceRow['description']) ?>
                        	</td>
                        	
                        	<td >
                        		<ul class="list-inline">
                        		<li>
								<a 
									href="<?php echo $this->acmUrl(
									    'editer',
									    'resource',
									    'admin',
									    array('resource_id' => $resourceRow['id']) 
									    )
									?>"
									class="btn btn-outline btn-info btn-sx" 
									role="button" 						
									data-placement="top" 
									data-toggle="tooltip"
									data-original-title="<?php echo $this->translate('resource_modifier') ?>"
									>
									<i class="fa fa-edit"></i>
									
								</a>                             		
                        		</li>
                        		<li>
                        		<a 
                        			href="<?php echo $this->acmUrl(
                        			    'supprimer',
                        			    'resource',
                        			    'admin',
                        			    array('resource_id' => $resourceRow['id']) 
                        			 )?>"                        			 
                        			class="btn btn-outline btn-danger btn-sx" 
									role="button" 						
									data-placement="top" 
									data-toggle="tooltip"									
									data-original-title="<?php echo $this->translate('resource_supprimer') ?>"                        			
                        			>
									<i class="fa fa-trash-o"></i>
									
								</a>
								</li>
                        	</td>
                        	
                        </tr>
                        <?php endforeach; ?>
                        <?php else  : ?>
                        <tr>
                        	<td class="dataTables_empty text-center" colspan="6" >
                        		<?php echo $this->translate('resources_list_empty')?>
                        	</td>
                        </tr>
                        <?php endif;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>    

