<?php  echo $this->breadcrumbs()->append($this->translate('home')) ; ?>

<?php //echo $this->translate('message1')?>
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Composants utilisés
            </div>
            
            <div class="panel-body">
            
                <div class="list-group">
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	Zend Framework 
                    	<span class="pull-right text-muted small"><em>version 1.12.6</em> </span>
                    </a>
                    
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	Jquery 
                    	<span class="pull-right text-muted small"><em>version 1.10.2</em> </span>
                    </a> 
                    
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	Bootstrap 
                    	<span class="pull-right text-muted small"><em>version 3.1.0</em> </span>
                    </a> 
                    
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	dataTables 
                    	<span class="pull-right text-muted small"><em>version 1.10.0</em> </span>
                    </a> 
                    
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	metisMenu 
                    	<span class="pull-right text-muted small"><em>version 1.0.1</em> </span>
                    </a> 
                    
                </div>
                
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->

    </div>
</div>

    <!-- Button to trigger modal -->
    <a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
     
    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
    </div>
    <div class="modal-body">
    <p>One fine body…</p>
    </div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
    </div>
    </div>
