<?php  echo $this->navigation()->breadcrumbs() ; ?>

<?php //echo $this->translate('message1')?>
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Composants utilisés
            </div>
            
            <div class="panel-body">
            
                <div class="list-group">
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	Zend Framework 
                    	<span class="pull-right text-muted small"><em>version 1.12.6</em> </span>
                    </a>
                    
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	Jquery 
                    	<span class="pull-right text-muted small"><em>version 1.10.2</em> </span>
                    </a> 
                    
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	Bootstrap 
                    	<span class="pull-right text-muted small"><em>version 3.1.0</em> </span>
                    </a> 
                    
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	dataTables 
                    	<span class="pull-right text-muted small"><em>version 1.10.0</em> </span>
                    </a> 
                    
                    <a href="#" class="list-group-item"> 
                    	<i class="fa fa-fw"></i> 
                    	metisMenu 
                    	<span class="pull-right text-muted small"><em>version 1.0.1</em> </span>
                    </a> 
                    
                </div>
                
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->

    </div>
</div>
