<?php
// Breadcrumbs
$this->breadcrumbs()->append($this->translate('user_password_update'));
?>


<?php 
	if (!empty($this->updatePasswordStatus)) : 	 
		$text =  $this->translate($this->updatePasswordMessage); 
		
		echo $this->alert($text, $this->updatePasswordStatus);
		
	 endif; 
?>

<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default">
		    
		    <div class="panel-body">
        
            <form role="form" method="post" id="<?php echo $this->form->getId() ?>">
                
				<div>
                    <label class="control-label" for="password1">
						<?php echo $this->form->getElement('password1')->getLabel(); ?>
					</label>

                    <div class="form-group input-group">
                        
                        <span class="input-group-addon"> 
                        	<i class="fa fa-unlock-alt"></i>
                        </span>	
						
						<?php  echo $this->form->getElement('password1')->renderViewHelper(); ?>
						
						<span class="input-group-btn">
						<?php  echo $this->formElementButtonInfo(
						    				$this->translate(
													$this->form->getElement('password1')->getDescription()
											)		
									)
						?>
                       	</span>
                       	
                    </div>
					
					<?php echo $this->FormElementErrors($this->form->getElement('password1')->getMessages())?>
						
				</div>

				<div>
                    <label class="control-label" for="password2">
						<?php echo $this->form->getElement('password2')->getLabel(); ?>
					</label>

                    <div class="form-group input-group">
                        
                        <span class="input-group-addon"> 
                        	<i class="fa fa-unlock-alt"></i>
                        </span>	
						
						<?php  echo $this->form->getElement('password2')->renderViewHelper(); ?>
						
						<span class="input-group-btn">
						<?php  echo $this->formElementButtonInfo(
						    				$this->translate(
													$this->form->getElement('password2')->getDescription()
											)		
									)
						?>
                       	</span>
                       	
                    </div>
					
					<?php echo $this->FormElementErrors($this->form->getElement('password2')->getMessages())?>
						
				</div>
				
                <div>
                    <button class="btn btn-default" type="submit">
                        <i class="fa fa-save fa-fw"></i>
						<?php echo $this->translate('action_save')?>
					</button>										
                </div>
                
            </form>
            </div>
            
        </div>
    </div>
</div>
