<?php
	// Breadcrumbs
	$this->breadcrumbs()->append($this->translate('roles'));
		
?>

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            
            <div class="panel-heading">
            	<?php echo $this->translate('role_lister') ?>
            	
            	<div class="pull-right" >
            		
					<a 
						href="<?php echo $this->acmUrl('editer', 'role', 'admin')?>"
						class="btn btn-primary btn-sx" 
						role="button" 						
						data-placement="top" 
						data-toggle="tooltip"
						data-original-title="<?php echo $this->translate('role_ajouter') ?>"
					>
						<i class="fa fa-plus-square"></i>						
					</a>     
            	</div>
            	<div class="row"></div>
            </div>
            
            <div class="panel-body">
				
				<?php echo $this->flashMessengerStatus() ?>
				            
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>
                                	<?php echo $this->translate('role_id')?>
                                </th>
                                
                                <th >
                                	<?php echo $this->translate('role_libelle')?>
                                </th>
                                
                                <th>
                                	<?php echo $this->translate('role_parent')?>
                                </th>
                                
                                <th>
                                	<?php echo $this->translate('actions')?>
                                </th>
                                
                            </tr>
                        </thead>
                        
                        <tbody>
                        <?php if ( is_array($this->rolesList) && count($this->rolesList)) : ?>
                        
                        <?php foreach ($this->rolesList as $role) : ?>
                        <tr>
                        	<td class="td-width-10">
                        		<?php echo $role['id'] ?>
                        	</td>
                        	
                        	<td class="td-width-40">
                        		<?php echo $this->escape($role['role']) ?>
                        	</td>
                        	
                        	<td class="td-width-30">
                        		<?php echo $this->escape($role['role_parent']) ?>
                        	</td>
                        	
                        	<td >
                        		<ul class="list-inline">
                        		<li>
								<a 
									href="<?php echo $this->acmUrl(
									    'editer',
									    'role',
									    'admin',
									    array('role_id' => $role['id']) 
									    )
									?>"
									class="btn btn-outline btn-info btn-sx" 
									role="button" 						
									data-placement="top" 
									data-toggle="tooltip"
									data-original-title="<?php echo $this->translate('role_modifier') ?>"
									>
									<i class="fa fa-edit"></i>
									
								</a>                             		
                        		</li>
                        		<li>
                        		<a 
                        			href="<?php echo $this->acmUrl(
                        			    'supprimer',
                        			    'role',
                        			    'admin',
                        			    array('role_id' => $role['id']) 
                        			 )?>"                        			 
                        			class="btn btn-outline btn-danger btn-sx" 
									role="button" 						
									data-placement="top" 
									data-toggle="tooltip"									
									data-original-title="<?php echo $this->translate('role_supprimer') ?>"                        			
                        			>
									<i class="fa fa-trash-o"></i>
									
								</a>
								</li>
                        	</td>
                        	
                        </tr>
                        <?php endforeach; ?>
                        <?php else  : ?>
                        <tr>
                        	<td class="dataTables_empty text-center" colspan="4" >
                        		<?php echo $this->translate('roles_list_empty')?>
                        	</td>
                        </tr>
                        <?php endif;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>    

