<?php  echo $this->doctype(); ?>

<html lang="<?php echo $this->language()?>">
<head>

<?php 
	
	// Title
	echo $this->headTitle($this->myApp()->getName());
	
	// CSS
	$this->headLink()->appendStylesheet($this->baseUrl('css/bootstrap/3.1.0/bootstrap.min.css'));
	$this->headLink()->appendStylesheet($this->baseUrl('css/font-awesome/4.0.3/css/font-awesome.min.css'));	
	$this->headLink()->appendStylesheet($this->baseUrl('css/flags/flags.css'));
	$this->headLink()->appendStylesheet($this->baseUrl('css/layout/sb-admin.css'));
	echo $this->headStyle();
	
	// JS
	$this->headScript()->prependFile( $this->baseUrl('js/bootstrap/3.1.0/bootstrap.min.js' ) );
	$this->headScript()->prependFile( $this->baseUrl('js/jquery/1.10.2/jquery.js' ) );
	
	$this->headScript()->appendFile( $this->baseUrl('js/jquery/plugins/metisMenu/jquery.metisMenu.js' ) );
	$this->headScript()->appendFile( $this->baseUrl('js/sb-admin/sb-admin.js' ) );
	echo $this->headScript();
	
	// Meta
	echo $this->headMeta();
	
	// link
	echo $this->headLink();
?>


</head>
<body>

	<div id="wrapper">

		<nav class="navbar navbar-default navbar-fixed-top" role="navigation" >
            
			<div class="navbar-header">
			
	        	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
	            	<span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	           	</button>
	           	
	           	<h1 id="navbar-header-app-name">
	            	<a class="navbar-brand" href="">
	            		<?php echo $this->myApp()->getName() ?>	            		
	            	</a>
	            </h1>
	            
			</div>
	
	        <ul class="nav navbar-top-links navbar-right">
	        	
	        	<li class="dropdown">
	            	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa flag flag-fr"></i>
						<i class="fa fa-caret-down"></i>
					</a>
	                
	                <ul class="dropdown-menu dropdown-user">
	                	<li>
	                		
	                		<a href="#">
	                			<i class="fa flag flag-gb"></i>
	                			English
	                		</a>
	                	</li>	
					</ul>
				</li>
	        
	        	<li class="dropdown">
	            	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
	                	<i class="fa fa-user fa-fw"></i>  
	                	Mourad MANSOUR
	                	<i class="fa fa-caret-down"></i>
					</a>
	                
	                <ul class="dropdown-menu dropdown-user">
	                	<li>
	                		<a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
	                    </li>
	                    
	                    <li>
	                    	<a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
	                    </li>
						
						<li class="divider"></li>
						
						<li>
							<a href="#"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
						</li>
					</ul>
				</li>
				
				
			</ul>
	            
	
	        <div class="navbar-default navbar-static-side" role="navigation">
	        	<div class="sidebar-collapse">
	        	<ul class="nav" id="side-menu">
					<?=$this->navigation()->menu()->renderPartial(null, 'sb-admin-vmenu.phtml')?>
				</ul>
						        		
				</div>
			</div>
	        
		</nav>
		
		
		<div id="page-wrapper" >
			
			<div class="row" >
				<div class="col-lg-12" id="page-wrapper-breadcrumb-id">
					<ol class="breadcrumb">						
						<li>
							<i class="fa fa-hand-o-right fa-fw"></i>
							<?php  echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->render() ?>
						</li>	
					</ol>
				</div>
				
			</div>
		
			<div class="row" >
				<div class="col-lg-12">
					<?php echo $this->layout()->content ?>
				</div>
			</div>
			
	    </div>

	</div>
	
	<footer class="footer">
		<p> 
			&copy; 2014 
			<a href="http://mansour-mourad.olympe.in">
				Mourad MANSOUR
			</a>	
		</p>
			 
	</footer>    
</body>
</html> 