<?php  echo $this->doctype(); ?>

<html lang="<?php echo $this->language()?>">
<head>

<?php 
	
	// Title
	echo $this->headTitle($this->myApp()->getName());
	
	// CSS
	$this->headLink()->appendStylesheet($this->baseUrl('css/bootstrap/3.1.0/bootstrap.min.css'));
	$this->headLink()->appendStylesheet($this->baseUrl('css/font-awesome/4.0.3/css/font-awesome.min.css'));	
	$this->headLink()->appendStylesheet($this->baseUrl('css/flags/flags.css'));
	$this->headLink()->appendStylesheet($this->baseUrl('css/layout/sb-admin.css'));
	echo $this->headStyle();
	
	// JS
	$this->headScript()->prependFile( $this->baseUrl('js/bootstrap/3.1.0/bootstrap.min.js' ) );
	$this->headScript()->prependFile( $this->baseUrl('js/jquery/1.10.2/jquery.js' ) );
		
	$this->headScript()->appendFile( $this->baseUrl('js/jquery/plugins/metisMenu/jquery.metisMenu.js' ) );
	$this->headScript()->appendFile( $this->baseUrl('js/sb-admin/sb-admin.js' ) );
	echo $this->headScript();
	
	// Meta
	echo $this->headMeta();
	
	// link
	echo $this->headLink();
?>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<div id="wrapper">

		<nav class="navbar navbar-default navbar-fixed-top" role="navigation" >
            
			<div class="navbar-header">
			
	        	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
	            	<span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	           	</button>
	           	
	           	<h1 id="navbar-header-app-name">
	            	<a class="navbar-brand" href="">
	            		<?php echo $this->myApp()->getName() ?>	            		
	            	</a>
	            </h1>
	            
			</div>
	
	        <ul class="nav navbar-top-links navbar-right">
	        	
	        	<li class="dropdown">
	            	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa flag flag-fr"></i>
						<i class="fa fa-caret-down"></i>
					</a>
	                
	                <ul class="dropdown-menu dropdown-user">
	                	<li>
	                		
	                		<a href="#">
	                			<i class="fa flag flag-gb"></i>
	                			English
	                		</a>
	                	</li>	
					</ul>
				</li>
	        
	        	<li class="dropdown">
	        	
	        		<?php if ($this->authIdentity()->hasIdentity()) : ?>
	            	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
	                	<i class="fa fa-user fa-fw"></i>  
	                	<?php echo $this->authIdentity()->getName() ?>
	                	<i class="fa fa-caret-down"></i>
					</a>
	                
	                <ul class="dropdown-menu dropdown-user">
	                	<li>
	                		<a href="<?php echo $this->acmUrl('view', 'profile', 'user')?>">
	                			<i class="fa fa-user fa-fw"></i> 
	                			<?php echo $this->translate('user_profile')?>
	                		</a>
	                    </li>
	                    
	                    <li>
	                		<a href="<?php echo $this->acmUrl('update-password', 'profile', 'user')?>">
	                			<i class="fa fa-lock fa-fw"></i> 
	                			<?php echo $this->translate('user_password_update')?>
	                		</a>
	                    
	                    </li>
						
						<li class="divider"></li>
						
						<li>
							<a href="<?php echo $this->acmUrl('logout', 'auth', 'user')?>">
								<i class="fa fa-sign-out fa-fw"></i> 
								<?php echo $this->translate('user_logout') ?>
							</a>
						</li>
					</ul>
					
					<?php else : ?>
						<a href="<?php echo $this->acmUrl('login', 'auth', 'user')?>">
								<i class="fa fa-sign-in fa-fw"></i> 
								<?php echo $this->translate('user_connect') ?>
						</a>
					<?php endif ?>
				</li>
				
				
			</ul>
	            
	
	        <div class="navbar-default navbar-static-side" role="navigation">
	        	<div class="sidebar-collapse">
	        	<ul class="nav" id="side-menu">
					<?php 
					echo $this->navigation()
					->menu()					
					->renderPartial(null, 'sb-admin-vmenu.phtml')
					
					?>
				</ul>
						        		
				</div>
			</div>
	        
		</nav>
		
		
		<div id="page-wrapper" >
			
			<div class="row" >
				<div class="col-lg-12" id="page-wrapper-breadcrumb-id">
					<ol class="breadcrumb">						
						<li>
							<i class="fa fa-hand-o-right fa-fw"></i>
							<?php  
							   echo $this->breadcrumbs()->setSeparator(' <i class="fa fa-angle-right fa-fw"></i>');							 
							?>
						</li>	
					</ol>
				</div>
				
			</div>
		
			<div class="row" >
				<div class="col-lg-12">
					<?php echo $this->layout()->content ?>
				</div>
			</div>
			
	    </div>
		
		<footer class="footer">
			<p> 
				&copy; 2014 
				<a href="http://mansour-mourad.olympe.in">
					Mourad MANSOUR
				</a>	
			</p>			 
		</footer>
	</div>	
</body>
</html> 